### ISSUE TITLE
Can we rename this repository?

### ISSUE THREAD

**Issue by GorgonMeducer** [lvgl/lv_port_an547_cm55_sim#1]
Hi @kisvegabor,

Can we rename this repository as `lv_sim_mdk_an547_cm55`?

I get this idea is because MPS3 is very expensive and highly likely that normal users won't have one. But for most MDK users, Corstone-300-FVP is the best (and the only) free simulation for the board which has an LCD and a touch screen. 

So if we keep calling this repository `lv_port_mps3_an547_cm55`, almost no one will get interesting in it as they have no such board called MPS3. 

To draw the attention of those MDK users, it is better to emphasize its simulation capability with the name `lv_sim_mdk_an547_cm55`.

What do you think?

**Comment by kisvegabor** [comment]
Hi,

> I get this idea is because MPS3 is very expensive and highly likely that normal users won't have one. But for most MDK users, Corstone-300-FVP is the best (and the only) free simulation for the board which has an LCD and a touch screen.

Makes sense, I've just renamed the repo.

**Comment by GorgonMeducer** [comment]
Thank you very much.

**Comment by kisvegabor** [comment]
Hi,

It [came up](https://forum.lvgl.io/t/add-support-in-the-simulator-for-additional-options/8053/27) to drop the `lv_sim_*` prefixes and use only `lv_port_*` so we shall perform an other rename. :slightly_frowning_face: 
The name of the simulator projects should be built like `lv_port_ + pc/win/linux + extra_info`.

So I suggest `lv_port_pc_mdk_an547_cm55` or as it's really a simulator (unlike the other PC projects) `lv_port_an547_cm55_sim`. What do you think?

**Comment by GorgonMeducer** [comment]
@kisvegabor  I prefer the later `lv_port_an547_cm55_sim`.

**Comment by kisvegabor** [comment]
Done, thank you!
