### ISSUE TITLE
Switching Branch

### ISSUE THREAD

**Issue by GorgonMeducer** [lvgl/lv_port_an547_cm55_sim#2]
@kisvegabor 
I have created a dedicated branch for LVGL8. Can you please switch the default branch to this one?

Thank you.

**Comment by kisvegabor** [comment]
Updated:
![image](https://user-images.githubusercontent.com/7599318/221971491-adbf6eb2-93a1-4d34-873e-a27c37086a82.png)

**Comment by GorgonMeducer** [comment]
Thank you very much @kisvegabor .
